ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'COURSE_MASTERY';
ALTER TYPE "GoalMetric" ADD VALUE IF NOT EXISTS 'QUESTIONS_COMPLETED';
ALTER TYPE "GoalStatus" ADD VALUE IF NOT EXISTS 'MISSED';
ALTER TYPE "GoalStatus" ADD VALUE IF NOT EXISTS 'PAUSED';
CREATE TYPE "GoalType" AS ENUM ('ACADEMIC_CWA', 'COURSE_STUDY_TIME', 'COURSE_MASTERY', 'PRACTICE_QUESTIONS', 'MANUAL_CHECKLIST');
CREATE TYPE "GoalTargetUnit" AS ENUM ('PERCENT', 'MINUTES', 'QUESTIONS', 'COUNT', 'MANUAL');
CREATE TYPE "GoalTrackingSource" AS ENUM ('ACADEMIC_RECORDS', 'PLANNER_SESSIONS', 'QUIZZES_AND_ASSESSMENTS', 'PRACTICE_ATTEMPTS', 'MANUAL');
ALTER TABLE "goals"
  ADD COLUMN "goal_type" "GoalType" NOT NULL DEFAULT 'MANUAL_CHECKLIST',
  ADD COLUMN "target_unit" "GoalTargetUnit" NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN "tracking_source" "GoalTrackingSource" NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN "starts_at" DATE;

-- Existing goals retain their values and remain manual unless a user explicitly changes template.
