"use server";
import { revalidatePath } from "next/cache";
import { requireAppUser } from "@/features/auth/queries";
import { requireActiveWritableSemester } from "@/features/academics/semester-state";
import { prisma } from "@/server/db";
import { syncGoalProgressSnapshots } from "@/features/goals/progress-sync";

export async function respondToAttendance(formData: FormData) { const { appUser } = await requireAppUser(); const id = String(formData.get("attendanceId")); const status = String(formData.get("status")); if (!["ATTENDED","MISSED","CANCELLED","EXCUSED"].includes(status)) throw new Error("Choose a valid attendance response."); const record = await prisma.attendanceRecord.findFirst({ where: { id, userId: appUser.id } }); if (!record) throw new Error("Attendance record not found."); await prisma.attendanceRecord.update({ where: { id }, data: { status: status as "ATTENDED", respondedAt: new Date(), source: "SELF_REPORTED" } }); revalidatePath("/academics"); }
export async function startStudyTimer(formData: FormData) { const { appUser } = await requireAppUser(); if (!appUser.activeSemesterId) throw new Error("Set an active semester first."); await requireActiveWritableSemester(appUser.id, appUser.activeSemesterId); const itemId = String(formData.get("studyPlanItemId")); const item = await prisma.studyPlanItem.findFirst({ where: { id: itemId, studyPlan: { userId: appUser.id, semesterId: appUser.activeSemesterId } } }); if (!item) throw new Error("Study session not found."); const start = new Date(); const end = item.scheduledStart && item.durationMinutes ? new Date(item.scheduledStart.getTime() + item.durationMinutes * 60_000) : null; await prisma.studySession.create({ data: { userId: appUser.id, semesterId: appUser.activeSemesterId, courseId: item.courseId, studyPlanItemId: item.id, plannedStart: item.scheduledStart, plannedEnd: end, startedAt: start, lastHeartbeatAt: start, status: "ACTIVE" } }); revalidatePath("/planner"); }
export async function stopStudyTimer(formData: FormData) { const { appUser } = await requireAppUser(); const id = String(formData.get("studySessionId")); const session = await prisma.studySession.findFirst({ where: { id, userId: appUser.id, status: "ACTIVE" } }); if (!session) throw new Error("Active study timer not found."); const end = new Date(); const minutes = Math.max(1, Math.floor((end.getTime() - (session.startedAt ?? end).getTime()) / 60_000)); await prisma.studySession.update({ where: { id }, data: { endedAt: end, durationMinutes: minutes, status: "COMPLETED", completionSource: "TIMER_TRACKED" } }); await syncGoalProgressSnapshots(appUser.id, session.semesterId); revalidatePath("/planner"); revalidatePath("/goals"); }
